server:
  port:8030
spring:
  profiles:
    active: dev, base-addi
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://goottjason.cafe24.com:3306/goottjason?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: goottjason
    password: mimi1570!!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
custom: # ???? ??
  genFileDirPath: c:/spring-temp/market # ?? ?? ??